version: "2"

linters:
  enable:
    - staticcheck
    - errcheck
    - govet
    - unused

linters-settings:
  staticcheck:
    checks:
      - "all"

issues:
  exclude-rules: []
  exclude-use-default: false